spring:
  application:
    name: expense
  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type: 
          descriptor:
            sql:
              BasicBinder: TRACE 
debug: true
